version: '3'

networks :
  ais-network:
    driver: bridge

services:

  ais-producer:
    build: "./nodered"
    depends_on:
      - message-bus
    volumes:
      - "./data/ais-producer:/data"
    networks:
      - ais-network

  ais-worker-database:
    build: "./nodered"
    depends_on:
      - message-bus
      - database
    volumes:
      - "./data/ais-worker-database:/data"
    networks:
      - ais-network

  ais-worker-database-mongo:
    build: "./nodered"
    depends_on:
      - message-bus
      - database-mongo
    volumes:
      - "./data/ais-worker-database-mongo:/data"
    networks:
      - ais-network

  ais-worker-file:
    build: "./nodered"
    depends_on:
      - message-bus
    volumes:
      - "./data/ais-worker-file:/data"
    networks:
      - ais-network

  message-bus:
    build: "./rabbitmq"
    networks:
      - ais-network

  database:
    image: influxdb
    volumes: 
      - "./data/database:/var/lib/influxdb"
    environment:
      - INFLUXDB_DB=aisdb
      - INFLUXDB_ADMIN=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=aisdb
      - INFLUXDB_PASSWORD=aisdb
    networks:
      - ais-network
      
  database-mongo:
    image: mongo
    # volumes: 
    #   - "./data/database-mongo:/data/db"
    networks:
      - ais-network
      
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=database-mongo
      # - ME_CONFIG_SITE_BASEURL=/mongo-express/
    networks:
      - ais-network
      
  grafana:
    image: "grafana/grafana"
    depends_on:
      - database
    volumes: 
      - "./data/grafana:/var/lib/grafana"
    environment:
      - GF_SERVER_ROOT_URL=http://localhost/grafana/
    networks:
      - ais-network

  nginx:
    build: "./nginx"
    depends_on:
      - grafana
      - message-bus
      - ais-producer
      - ais-worker-database
      - ais-worker-file
      - ais-worker-database-mongo
      - database-mongo
      - mongo-express
    ports:
      - "80:80"
    networks:
      - ais-network

