version: '3'

networks :
  ais-network:
    driver: bridge


services:

  ais-producer:
    build: "./nodered"
    depends_on:
      - message_bus
    restart: on-failure
    volumes:
      - "./data/ais-producer:/data"
    networks:ais-network

  ais-worker-database:
    build: "./nodered"
    depends_on:
      - message_bus
      - database
    restart: on-failure
    volumes:
      - "./data/ais-worker-database:/data"
    networks:
      - ais-network

  ais-worker-file:
    build: "./nodered"
    depends_on:
      - message_bus
    restart: on-failure
    volumes:
      - "./data/ais-worker-file:/data"
    networks:
      - ais-network

  message_bus:
    build: "./rabbitmq"
    restart: on-failure
    networks:
      - ais-network

  database:
    image: influxdb
    restart: on-failure
    volumes: 
      - "./data/database:/var/lib/influxdb"
    environment:
      - INFLUXDB_DB=aisdb
      - INFLUXDB_ADMIN=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=aisdb
      - INFLUXDB_PASSWORD=aisdb
    networks:
      - ais-network
      
  grafana:
    image: "grafana/grafana"
    depends_on:
      - database
    restart: on-failure
    volumes: 
      - "./data/grafana:/var/lib/grafana"
    ports:
      - "3000:3000"
    networks:
      - ais-network

  nginx:
    build: "./nginx"
    depends_on:
      - grafana
      - message_bus
      - ais-producer
      - ais-worker-database
      - ais-worker-file
    restart: on-failure
    ports:
      - "80:80"
    networks:
      - ais-network
