version: '3'

networks :
  logging-network:
    driver: bridge

services:

  logspout:
    image: gliderlabs/logspout:latest
    command: 'udp://logstash:5000'
    labels:
      - "nolog=true"
    environment:
      - "EXCLUDE_LABEL=nolog"
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    depends_on:
      - logstash
    networks:
      - logging-network

  logstash:
    image: logstash:6.7.0
    labels:
      - "nolog=true"
    environment:
      - "STDOUT=true"
    depends_on:
      - kibana
    command: 'logstash -e "input { udp { port => 5000 } } filter { if [docker][image] =~ /^logstash/ {  drop { } } } output { elasticsearch { hosts => elasticsearch } }"'
    networks:
      - logging-network

  kibana:
    image: kibana:6.7.0
    labels:
      - "nolog=true"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - logging-network

  elasticsearch:
    image: elasticsearch:6.7.0
    labels:
      - "nolog=true"
    volumes:
      - "./data/elasticsearch:/usr/share/elasticsearch/data"
    networks:
      - logging-network
