FROM nodered/node-red-docker

RUN npm install node-red-contrib-ais
RUN npm install node-red-contrib-influxdb
RUN npm install node-red-contrib-amqp
RUN npm install node-red-contrib-azure-eventhub-receive
RUN npm install node-red-contrib-counter
RUN npm install node-red-dashboard
RUN npm install node-red-contrib-msg-speed
RUN npm install node-red-contrib-web-worldmap